name: ollama
services:
  ollama:
    image: ollama/ollama:latest
    # pull_policy: always
    container_name: ollama
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q4_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${APPDATA}/ollama:/root/.ollama
    ports:
      - "11434:11434" # Add this line to expose the port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    # pull_policy: always
    container_name: open-webui
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL="http://searxng:8080/search?q=<query>"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${APPDATA}/open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8081:8080" # Add this line to expose the port

  searxng:
    image: searxng/searxng:latest
    # pull_policy: always
    container_name: searxng
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${APPDATA}/searxng:/etc/searxng:rw
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: unless-stopped
    ports:
      - "8082:8080" # Add this line to expose the port
