apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  project: default
  sources:
    - chart: descheduler
      repoURL: "https://kubernetes-sigs.github.io/descheduler/"
      targetRevision: 0.33.0
      helm:
        valueFiles:
          - $values/k8s-deploy/descheduler/values.yaml
    - repoURL: "https://github.com/phuchoang2603/self-host.git"
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
