{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "my-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "my-chart.fullname" . }}
          port: {{ .Values.service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "my-chart.fullname" . }}-force-https
  namespace: {{ .Release.Namespace }}
spec:
  service:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "my-chart.fullname" . }}-transport
  namespace: {{ .Release.Namespace }}
spec:
  rootCAsSecrets:
    - wildcart-tls
{{- end }}
