---
###############################################################
#                   Authelia configuration                    #
###############################################################
theme: dark #light/dark

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  issuer: 'vps.phuchoang.sbs'

identity_validation:
  reset_password:
    jwt_secret: 'W4TKg7EFZxBz1L0vlv36gTc5QpmkgooPR7Sbu1OLgEXrCep2TfoqMBV6f4OlB8tm'

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.vps.phuchoang.sbs" #This should be your authentication URL
      policy: bypass
    - domain: "*.vps.phuchoang.sbs" #example to protect all subdomains under top-level domain
      policy: two_factor

session:
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: 'v0fSMVyClXxo87DiVJzkbCILea0Xhh40uht9dRfpTXPA7vz4YBC7foyqQKRAzzui'

  cookies:
    - name: 'authelia_session'
      domain: 'vps.phuchoang.sbs'  # Should match whatever your root protected domain is
      authelia_url: 'https://auth.vps.phuchoang.sbs'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: 'redis'
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'zvtOyR6fGq5ZRCwZkTMfxq8TJsf7GqalE6pabd4BBiA801gmbVxgSlZSphJhtezW'
  local:
    path: '/config/db.sqlite3'

notifier:
  smtp:
    username: 'auth_timz'
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: 'phuc26032006'
    address: 'smtp://mail.smtp2go.com:2525'
    sender: 'auth@phuchoang.sbs'
...