version: "3.9"
name: media-stack
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent

    networks:              
      - mynetwork

    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - xpenology:/data

    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    networks:
      - mynetwork
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - xpenology:/data
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    volumes:
      - sonarr-config:/config
      - xpenology:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr

    # Uncomment below if vpn is enabled
    # depends_on:               # Uncomment this line if vpn is enabled
    #   - vpn                   # Uncomment this line if vpn is enabled
    # network_mode: service:vpn # Uncomment this line if vpn is enabled

    networks:               # Comment this line if vpn is enabled
      - mynetwork           # Comment this line if vpn is enabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config

    # Comment below ports if VPN is enabled.
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Asia/Saigon
    ports:
        - 5055:5055
    volumes:
        - jellyseerr-config:/app/config
        - xpenology:/data
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - recyclarr-config:/config
    environment:
      - TZ=Asia/Saigon
    restart: unless-stopped
  
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    volumes:
      - bazarr-config:/config
      - xpenology:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    volumes:
      - readarr-config:/config
      - xpenology:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /home/phuc/.config/calibre/config:/config #change before the ':' if necessary
      - /home/phuc/.config/calibre/plugins:/plugins #change before the ':' if necessary      - 
      - xpenology:/data #this is where your ebooks will end up
    ports:
      - 8082:8080 #change before the ':' if necessary
      - 8081:8081 #change before the ':' if necessary
    restart: unless-stopped
    networks:
      - mynetwork

  speakarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: speakarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    volumes:
      - speakarr-config:/config
      - xpenology:/data
    ports:
      - 8788:8787
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Saigon
    ports:
      - 13378:80
    volumes:
      - /root/.config/audiobookshelf/config:/config
      - /root/.config/audiobookshelf/metadata:/metadata
      - xpenology:/data
    restart: unless-stopped

  
volumes:
  xpenology:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.2,nfsvers=4"
      device: ":/volume1/xpenology/Synology"
  qbittorrent-config: /root/.config/qbittorrent
  radarr-config: /root/.config/radarr
  sonarr-config: /root/.config/sonarr
  prowlarr-config: /root/.config/prowlarr
  jellyseerr-config: /root/.config/jellyseerr
  recyclarr-config: /root/.config/recyclarr
  bazarr-config: /root/.config/bazarr
  readarr-config: /root/.config/readarr
  speakarr-config: /root/.config/speakarr

networks:
  mynetwork:
    external: true