# Ref: https://trash-guides.info/
name: media-stack
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - WEBUI_PORT=5080
    volumes:
      - ./qbittorrent/config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config:/config
      - ${MEDIA_FOLDER}:/data
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    networks:               # Comment this line if vpn is enabled
      - media           # Comment this line if vpn is enabled
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - media
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=0
      - PGID=0
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - ./tdarr/logs:/app/logs
      - ${MEDIA_FOLDER}:/media
      - transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


  # recyclarr:
  #   image: ghcr.io/recyclarr/recyclarr:latest
  #   container_name: recyclarr
  #   networks:
  #     - media
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=${TZ}
  #   volumes:
  #     - ./recyclar/config:/config
  #   restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    environment:
      - PGID=0
      - PUID=0
      - TZ=${TZ}
    hostname: jellyfin
    image: jellyfin/jellyfin
    network_mode: 'host'
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ${MEDIA_FOLDER}:/data
      - jellyfin_cache:/cache
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  transcode_cache:
  jellyfin_cache:

networks:
  media:
    external: true
