apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudnative-pg
  sources:
    - chart: cloudnative-pg
      repoURL: "https://cloudnative-pg.github.io/charts"
      targetRevision: 0.26.0
      helm:
        valueFiles:
          - $values/k8s-deploy/cloudnative-pg/values.yaml
    - repoURL: "https://github.com/phuchoang2603/self-host.git"
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
