{{- if .Values.cloud.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud
  namespace: argo-cd
spec:
  project: default
  destination:
    server: {{ .Values.global.destinationServer | quote }}
    namespace: {{ .Values.cloud.destinationNamespace | quote }}
  source:
    repoURL: {{ default .Values.global.repoURL .Values.cloud.repoURL | quote }}
    path: {{ .Values.cloud.path | quote }}
    targetRevision: {{ default .Values.global.targetRevision .Values.cloud.targetRevision | quote }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
{{- end }}
