# Ref: https://trash-guides.info/
name: media-stack
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - WEBUI_PORT=5080
    volumes:
      - ${APPDATA}/qbittorrent/config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    networks:
      - media
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - media
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  syncify:
    container_name: syncify
    image: thewicklowwolf/syncify:latest
    networks:
      - media
    volumes:
      - ${APPDATA}/syncify/config:/syncify/config
      - ${MEDIA_FOLDER}/Music/:/syncify/downloads
    ports:
      - 5000:5000
    environment:
      - PUID=0
      - PGID=0
      - thread_limit=4
      - crop_album_art=true
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    networks:
      - media
    ports:
      - 8096:8096
    restart: unless-stopped
    environment:
      - PGID=0
      - PUID=0
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/jellyfin/config:/config
      - ${MEDIA_FOLDER}:/data
      - jellyfin_cache:/cache

volumes:
  jellyfin_cache:

networks:
  media:
    external: true
