{{- /*
  Loop through all defined applications in .Values.applications
  and create an ArgoCD Application resource for each.
*/}}
{{- range $appName, $appConfig := .Values.applications }}
{{- if $appConfig.enabled }}
# --- ArgoCD Application for {{ $appName }} ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName | quote }}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $appConfig.destinationNamespace | quote }}
  sources:
    # Main source for the Helm Chart
    - chart: {{ $appConfig.chartName | quote }}
      path: {{ $appConfig.path | quote }}
      repoURL: {{ $appConfig.chartURL | default $.Values.global.gitRepoURL | quote }}
      targetRevision: {{ $appConfig.chartTargetRevision | default $.Values.global.gitTargetRevision | quote }}
      helm:
        valueFiles:
          - $values/{{ $appConfig.valuesFile }}
    - repoURL: {{ $appConfig.valuesURL | default $.Values.global.gitRepoURL | quote }}
      targetRevision: {{ $appConfig.valuesTargetRevision | default $.Values.global.gitTargetRevision | quote }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- if $appConfig.nfsPV }}
  {{- range $pvName, $pvConfig := $appConfig.nfsPV }}
# --- PersistentVolume for {{ $appName }}: {{ $pvName }} ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s" $appName $pvName }}
spec:
  storageClassName: {{ $pvConfig.storageClassName | quote }}
  capacity:
    storage: {{ $pvConfig.size | quote }}
  accessModes:
    - {{ default "ReadWriteOnce" $pvConfig.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ $pvConfig.policy | default "Retain" | quote }}
  nfs:
    path: {{ $pvConfig.path | quote }}
    server: {{ $pvConfig.host | default $.Values.global.nfs.server | quote }}
    readOnly: false
---
{{- if $pvConfig.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $appName $pvName }}-pvc
  namespace: {{ $appConfig.destinationNamespace | quote }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" $pvConfig.accessMode | quote }}
  storageClassName: {{ $pvConfig.storageClassName | quote }}
  resources:
    requests:
      storage: {{ $pvConfig.size | quote }}
{{- end }} {{/* End of if pvc */}}
  {{- end }}{{/* End of pvConfig loop */}}
{{- end }}{{/* End of if nfsPV */}}
{{- end }}{{/* End of if enabled */}}
{{- end }}{{/* End of appConfig loop */}}
