apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-vchord-db
spec:
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-postgres-user
        connectionLimit: -1
        inherit: true
  instances: 1
  imageName: tensorchord/cloudnative-vectorchord:16.9-0.4.3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  storage:
    size: 20Gi
    storageClass: ""
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  monitoring:
    enablePodMonitor: false
