apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
type: kubernetes.io/basic-auth
stringData:
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PASSWORD: immich
  username: immich
  password: immich
