{{- range .Values.persistence.claims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-chart.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "my-chart.labels" $ | nindent 4 }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
